# Generated by Django 3.0.8 on 2020-07-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_useractivity_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
