# Generated by Django 3.0.8 on 2020-07-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_useractivity_userdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='User',
        ),
    ]
