# Generated by Django 3.0.8 on 2020-07-08 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_auto_20200707_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_user', to='user_management.UserData')),
            ],
            options={
                'verbose_name_plural': 'ActivityPeriod',
            },
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
